// <auto-generated />
namespace Skill_PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class addpasswordfieldinusermodel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addpasswordfieldinusermodel));
        
        string IMigrationMetadata.Id
        {
            get { return "202007221401547_add password field in user model"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
