// <auto-generated />
namespace Skill_PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Modify_Log_Job_Price_Time : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modify_Log_Job_Price_Time));
        
        string IMigrationMetadata.Id
        {
            get { return "202108061229474_Modify_Log_Job_Price_Time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
