// <auto-generated />
namespace Skill_PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ShiftReport_Workload_Modify : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ShiftReport_Workload_Modify));
        
        string IMigrationMetadata.Id
        {
            get { return "202108081943074_ShiftReport_Workload_Modify"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
