// <auto-generated />
namespace Skill_PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Modify_NewJob_Workload_ShiftReport_RunningJob : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Modify_NewJob_Workload_ShiftReport_RunningJob));
        
        string IMigrationMetadata.Id
        {
            get { return "202108222033063_Modify_NewJob_Workload_ShiftReport_RunningJob"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
