// <auto-generated />
namespace Skill_PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class readdtotal_timeinassign_time : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(readdtotal_timeinassign_time));
        
        string IMigrationMetadata.Id
        {
            get { return "202208230732426_re-add total_time in assign_time"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
