// <auto-generated />
namespace Skill_PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class removeteamfromimageTime : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(removeteamfromimageTime));
        
        string IMigrationMetadata.Id
        {
            get { return "202208231015493_remove team from imageTime"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
