// <auto-generated />
namespace Skill_PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Locaddedinjoblist : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Locaddedinjoblist));
        
        string IMigrationMetadata.Id
        {
            get { return "202302122255060_Loc added in job list"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
