// <auto-generated />
namespace Skill_PMS.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Misc_Taskadded : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Misc_Taskadded));
        
        string IMigrationMetadata.Id
        {
            get { return "202406091554124_Misc_Task added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
